apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: corredor
  name: corredor
  namespace: corredor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corredor
  template:
    metadata:
      labels:
        app: corredor
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - mountPath: "/etc/luiz/"
            name: volume-corredor
      volumes:
        - name: volume-corredor
          persistentVolumeClaim:
            claimName: pvc-corredor
