apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sala
  name: sala
  namespace: sala
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sala
  template:
    metadata:
      labels:
        app: sala
    spec:
      containers:
      - image: nginx
        name: nginx
