apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: banheiro
  name: banheiro
  namespace: banheiro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banheiro
  template:
    metadata:
      labels:
        app: banheiro
    spec:
      containers:
      - image: nginx
        name: nginx
