apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarto
  name: quarto
  namespace: quarto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarto
  template:
    metadata:
      labels:
        app: quarto
    spec:
      containers:
      - image: nginx
        name: nginx
