apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-corredor
  namespace: corredor
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
